# port #
server:
  port: 30000
  shutdown: graceful
# Spring.cloud.feign #
spring:
  cloud:
    openfeign:
      httpclient:
        enabled: true
        connection-timeout: 5000 #connection-time out
  data:
    mongodb:
      host: localhost
      port: 27017
      database: car_info
      username: carinfo
      password: WinkAldaold123!